# Generated by Django 5.2.1 on 2025-05-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category_id', models.IntegerField()),
                ('sub_category_id', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=150)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
